package currencies

type Currency string

const (
	AMD Currency = "AMD"        //	ARMENIA	Armenian Dram
	ANG Currency = "ANG"        //	CURAÇAO	Netherlands Antillean Guilder SINT MAARTEN (DUTCH PART)	Netherlands Antillean Guilder
	AOA Currency = "AOA"        //	ANGOLA	Kwanza
	ARS Currency = "ARS"        //	ARGENTINA	Argentine Peso
	AUD Currency = "AUD"        //	AUSTRALIA	Australian Dollar
	AWG Currency = "AWG"        //	ARUBA	Aruban Florin
	AZN Currency = "AZN"        //	AZERBAIJAN	Azerbaijanian Manat
	BAM Currency = "BAM"        //	BOSNIA AND HERZEGOVINA	Convertible Mark
	BBD Currency = "BBD"        //	BARBADOS	Barbados Dollar
	BDT Currency = "BDT"        //	BANGLADESH	Taka
	BGN Currency = "BGN"        //	BULGARIA	Bulgarian Lev
	BHD Currency = "BHD"        //	BAHRAIN	Bahraini Dinar
	BIF Currency = "BIF"        //	BURUNDI	Burundi Franc
	BMD Currency = "BMD"        //	BERMUDA	Bermudian Dollar
	BND Currency = "BND"        //	BRUNEI DARUSSALAM	Brunei Dollar
	BOB Currency = "BOB"        //	BOLIVIA (PLURINATIONAL STATE OF)	Boliviano
	BOV Currency = "BOV"        //	BOLIVIA (PLURINATIONAL STATE OF)	Mvdol
	BRL Currency = "BRL"        //	BRAZIL	Brazilian Real
	BSD Currency = "BSD"        //	BAHAMAS (THE)	Bahamian Dollar
	BTN Currency = "BTN"        //	BHUTAN	Ngultrum
	BWP Currency = "BWP"        //	BOTSWANA	Pula
	BYR Currency = "BYR"        //	BELARUS	Belarusian Ruble
	BZD Currency = "BZD"        //	BELIZE	Belize Dollar
	CAD Currency = "CAD"        //	CANADA	Canadian Dollar
	CDF Currency = "CDF"        //	CONGO (THE DEMOCRATIC REPUBLIC OF THE)	Congolese Franc
	CHE Currency = "CHE"        //	SWITZERLAND	WIR Euro
	CHF Currency = "CHF"        //	SWITZERLAND	Swiss Franc
	CHW Currency = "CHW"        //	SWITZERLAND	WIR Franc
	CLF Currency = "CLF"        //	CHILE	Unidad de Fomento
	CLP Currency = "CLP"        //	CHILE	Chilean Peso
	CNY Currency = "CNY"        //	CHINA	Yuan Renminbi
	COP Currency = "COP"        //	COLOMBIA	Colombian Peso
	COU Currency = "COU"        //	COLOMBIA	Unidad de Valor Real
	CRC Currency = "CRC"        //	COSTA RICA	Costa Rican Colon
	CUC Currency = "CUC"        //	CUBA	Peso Convertible
	CUP Currency = "CUP"        //	CUBA	Cuban Peso
	CVE Currency = "CVE"        //	CABO VERDE	Cabo Verde Escudo
	CZK Currency = "CZK"        //	CZECH REPUBLIC (THE)	Czech Koruna
	DJF Currency = "DJF"        //	DJIBOUTI	Djibouti Franc
	DKK Currency = "DKK"        //	DENMARK	Danish Krone
	DOP Currency = "DOP"        //	DOMINICAN REPUBLIC (THE)	Dominican Peso
	DZD Currency = "DZD"        //	ALGERIA	Algerian Dinar
	EGP Currency = "EGP"        //	EGYPT	Egyptian Pound
	ERN Currency = "ERN"        //	ERITREA	Nakfa
	ETB Currency = "ETB"        //	ETHIOPIA	Ethiopian Birr
	EUR Currency = "EUR"        //	Euro
	FJD Currency = "FJD"        //	FIJI	Fiji Dollar
	FKP Currency = "FKP"        //	FALKLAND ISLANDS (THE) [MALVINAS]	Falkland Islands Pound
	GBP Currency = "GBP"        //	UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)	Pound Sterling
	GEL Currency = "GEL"        //	GEORGIA	Lari
	GHS Currency = "GHS"        //	GHANA	Ghana Cedi
	GIP Currency = "GIP"        //	GIBRALTAR	Gibraltar Pound
	GMD Currency = "GMD"        //	GAMBIA (THE)	Dalasi
	GNF Currency = "GNF"        //	GUINEA	Guinea Franc
	GTQ Currency = "GTQ"        //	GUATEMALA	Quetzal
	GYD Currency = "GYD"        //	GUYANA	Guyana Dollar
	HKD Currency = "HKD"        //	HONG KONG	Hong Kong Dollar
	HNL Currency = "HNL"        //	HONDURAS	Lempira
	HRK Currency = "HRK"        //	CROATIA	Kuna
	HTG Currency = "HTG"        //	HAITI	Gourde
	HUF Currency = "HUF"        //	HUNGARY	Forint
	IDR Currency = "IDR"        //	INDONESIA	Rupiah
	ILS Currency = "ILS"        //	ISRAEL	New Israeli Sheqel
	INR Currency = "INR"        //	INDIA	Indian Rupee
	IQD Currency = "IQD"        //	IRAQ	Iraqi Dinar
	IRR Currency = "IRR"        //	IRAN (ISLAMIC REPUBLIC OF)	Iranian Rial
	ISK Currency = "ISK"        //	ICELAND	Iceland Krona
	JMD Currency = "JMD"        //	JAMAICA	Jamaican Dollar
	JOD Currency = "JOD"        //	JORDAN	Jordanian Dinar
	JPY Currency = "JPY"        //	JAPAN	Yen
	KES Currency = "KES"        //	KENYA	Kenyan Shilling
	KGS Currency = "KGS"        //	KYRGYZSTAN	Som
	KHR Currency = "KHR"        //	CAMBODIA	Riel
	KMF Currency = "KMF"        //	COMOROS (THE)	Comoro Franc
	KPW Currency = "KPW"        //	KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)	North Korean Won
	KRW Currency = "KRW"        //	KOREA (THE REPUBLIC OF)	Won
	KWD Currency = "KWD"        //	KUWAIT	Kuwaiti Dinar
	KYD Currency = "KYD"        //	CAYMAN ISLANDS (THE)	Cayman Islands Dollar
	KZT Currency = "KZT"        //	KAZAKHSTAN	Tenge
	LAK Currency = "LAK"        //	LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)	Kip
	LBP Currency = "LBP"        //	LEBANON	Lebanese Pound
	LKR Currency = "LKR"        //	SRI LANKA	Sri Lanka Rupee
	LRD Currency = "LRD"        //	LIBERIA	Liberian Dollar
	LSL Currency = "LSL"        //	LESOTHO	Loti
	LYD Currency = "LYD"        //	LIBYA	Libyan Dinar
	MAD Currency = "MAD"        //	MOROCCO	Moroccan Dirham
	MDL Currency = "MDL"        //	MOLDOVA (THE REPUBLIC OF)	Moldovan Leu
	MGA Currency = "MGA"        //	MADAGASCAR	Malagasy Ariary
	MKD Currency = "MKD"        //	MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)	Denar
	MMK Currency = "MMK"        //	MYANMAR	Kyat
	MNT Currency = "MNT"        //	MONGOLIA	Tugrik
	MOP Currency = "MOP"        //	MACAO	Pataca
	MRO Currency = "MRO"        //	MAURITANIA	Ouguiya
	MUR Currency = "MUR"        //	MAURITIUS	Mauritius Rupee
	MVR Currency = "MVR"        //	MALDIVES	Rufiyaa
	MWK Currency = "MWK"        //	MALAWI	Malawi Kwacha
	MXN Currency = "MXN"        //	MEXICO	Mexican Peso
	MXV Currency = "MXV"        //	MEXICO	Mexican Unidad de Inversion (UDI)
	MYR Currency = "MYR"        //	MALAYSIA	Malaysian Ringgit
	MZN Currency = "MZN"        //	MOZAMBIQUE	Mozambique Metical
	NAD Currency = "NAD"        //	NAMIBIA	Namibia Dollar
	NGN Currency = "NGN"        //	NIGERIA	Naira
	NIO Currency = "NIO"        //	NICARAGUA	Cordoba Oro
	NOK Currency = "NOK"        //	NORWAY	Norwegian Krone
	NPR Currency = "NPR"        //	NEPAL	Nepalese Rupee
	NZD Currency = "NZD"        //	NEW ZEALAND	New Zealand Dollar
	OMR Currency = "OMR"        //	OMAN	Rial Omani
	PAB Currency = "PAB"        //	PANAMA	Balboa
	PEN Currency = "PEN"        //	PERU	Sol
	PGK Currency = "PGK"        //	PAPUA NEW GUINEA	Kina
	PHP Currency = "PHP"        //	PHILIPPINES (THE)	Philippine Peso
	PKR Currency = "PKR"        //	PAKISTAN	Pakistan Rupee
	PLN Currency = "PLN"        //	POLAND	Zloty
	PYG Currency = "PYG"        //	PARAGUAY	Guarani
	QAR Currency = "QAR"        //	QATAR	Qatari Rial
	RON Currency = "RON"        //	ROMANIA	Romanian Leu
	RSD Currency = "RSD"        //	SERBIA	Serbian Dinar
	RUB Currency = "RUB"        //	RUSSIAN FEDERATION (THE)	Russian Ruble
	RWF Currency = "RWF"        //	RWANDA	Rwanda Franc
	SAR Currency = "SAR"        //	SAUDI ARABIA	Saudi Riyal
	SBD Currency = "SBD"        //	SOLOMON ISLANDS	Solomon Islands Dollar
	SCR Currency = "SCR"        //	SEYCHELLES	Seychelles Rupee
	SDG Currency = "SDG"        //	SUDAN (THE)	Sudanese Pound
	SEK Currency = "SEK"        //	SWEDEN	Swedish Krona
	SGD Currency = "SGD"        //	SINGAPORE	Singapore Dollar
	SHP Currency = "SHP"        //	SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA	Saint Helena Pound
	SLL Currency = "SLL"        //	SIERRA LEONE	Leone
	SOS Currency = "SOS"        //	SOMALIA	Somali Shilling
	SRD Currency = "SRD"        //	SURINAME	Surinam Dollar
	SSP Currency = "SSP"        //	SOUTH SUDAN	South Sudanese Pound
	STD Currency = "STD"        //	SAO TOME AND PRINCIPE	Dobra
	SVC Currency = "SVC"        //	EL SALVADOR	El Salvador Colon
	SYP Currency = "SYP"        //	SYRIAN ARAB REPUBLIC	Syrian Pound
	SZL Currency = "SZL"        //	SWAZILAND	Lilangeni
	THB Currency = "THB"        //	THAILAND	Baht
	TJS Currency = "TJS"        //	TAJIKISTAN	Somoni
	TMT Currency = "TMT"        //	TURKMENISTAN	Turkmenistan New Manat
	TND Currency = "TND"        //	TUNISIA	Tunisian Dinar
	TOP Currency = "TOP"        //	TONGA	Pa’anga
	TRY Currency = "TRY"        //	TURKEY	Turkish Lira
	TTD Currency = "TTD"        //	TRINIDAD AND TOBAGO	Trinidad and Tobago Dollar
	TWD Currency = "TWD"        //	TAIWAN (PROVINCE OF CHINA)	New Taiwan Dollar
	TZS Currency = "TZS"        //	TANZANIA, UNITED REPUBLIC OF	Tanzanian Shilling
	UAH Currency = "UAH"        //	UKRAINE	Hryvnia
	UGX Currency = "UGX"        //	UGANDA	Uganda Shilling
	USD Currency = "USD"        //	UNITED STATES OF AMERICA (THE)	US Dollar
	USN Currency = "USN"        //	UNITED STATES OF AMERICA (THE)	US Dollar (Next day)
	UYI Currency = "UYI"        //	URUGUAY	Uruguay Peso en Unidades Indexadas (URUIURUI)
	UYU Currency = "UYU"        //	URUGUAY	Peso Uruguayo
	UZS Currency = "UZS"        //	UZBEKISTAN	Uzbekistan Sum
	VEF Currency = "VEF"        //	VENEZUELA (BOLIVARIAN REPUBLIC OF)	Bolívar
	VND Currency = "VND"        //	VIET NAM	Dong
	VUV Currency = "VUV"        //	VANUATU	Vatu
	WST Currency = "WST"        //	SAMOA	Tala
	XAF Currency = "XAF"        //	CAMEROON	CFA Franc BEAC
	XAG Currency = "XAG"        //	ZZ11_Silver	Silver
	XAU Currency = "XAU"        //	ZZ08_Gold	Gold
	XBA Currency = "XBA"        //	ZZ01_Bond Markets Unit European_EURCO	Bond Markets Unit European Composite Unit (EURCO)
	XBB Currency = "XBB"        //	ZZ02_Bond Markets Unit European_EMU-6	Bond Markets Unit European Monetary Unit (E.M.U.-6)
	XBC Currency = "XBC"        //	ZZ03_Bond Markets Unit European_EUA-9	Bond Markets Unit European Unit of Account 9 (E.U.A.-9)
	XBD Currency = "XBD"        //	ZZ04_Bond Markets Unit European_EUA-17	Bond Markets Unit European Unit of Account 17 (E.U.A.-17)
	XCD Currency = "XCD"        //	ANGUILLA	East Caribbean Dollar
	XDR Currency = "XDR"        //	INTERNATIONAL MONETARY FUND (IMF) 	SDR (Special Drawing Right)
	XOF Currency = "XOF"        //	BENIN	CFA Franc BCEAO
	XPD Currency = "XPD"        //	ZZ09_Palladium	Palladium
	XPF Currency = "XPF"        //	FRENCH POLYNESIA	CFP Franc
	XPT Currency = "XPT"        //	ZZ10_Platinum	Platinum
	XSU Currency = "XSU"        //	SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"Sucre
	XTS Currency = "XTS"        //	ZZ06_Testing_Code	Codes specifically reserved for testing purposes
	XUA Currency = "XUA"        //	MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP	ADB Unit of Account
	XXX Currency = "XXX"        //	ZZ07_No_Currency	The codes assigned for transactions where no currency is involved
	YER Currency = "YER"        //	YEMEN	Yemeni Rial
	ZAR Currency = "ZAR"        //	SOUTH AFRICA	Rand
	ZMW Currency = "ZMW"        //	ZAMBIA	Zambian Kwacha
	ZWL Currency = "ZWL"        //	ZIMBABWE	Zimbabwe Dollar

)